### PR TITLE
Making package compatible with language_level=3

### PR DESCRIPTION
**Pull request by shz9**
Hey,

I tried installing `phasedibd` on the compute cluster and noticed that there are compilation errors depending on which cython version you use. For example, if I use `cython==3.0.2`, I get compilation errors along the line of:

```
Error compiling Cython file:
------------------------------------------------------------
...
from libc.stdint cimport uint8_t, uint16_t, uint32_t
from libc.stdio cimport *
from haplotype_alignment cimport HaplotypeAlignment
^
------------------------------------------------------------

phasedibd/compressed_haplotype_alignment.pxd:3:0: 'haplotype_alignment.pxd' not found
```

In other words, the compiler is not finding the relevant `.pxd` file.  This issue does not arise when working with `cython==0.29.23` as well as earlier versions of `python3`. I noticed that what is driving the differences in behavior is the default assignment of the `language_level` compiler flag. Earlier versions of `cython` and `python3` use `language_level="2"` by default (if not specified). In newer versions, they use `language_level="3"`. So, the first change I made was I explicitly set the `language_level` in the new `setup.py` file to avoid these issues:

```python
ext_modules=cythonize([Extension('phasedibd.*', ['phasedibd/*.pyx'], include_dirs=[np.get_include()])], language_level="3")
```

However, this raises other issues. In python3, import paths are expected to be absolute (issue and its relevance to `language_level` is discussed [here](https://stackoverflow.com/questions/56115159/pxd-relative-cimport-works-for-language-level-2-but-not-for-3)). So, I had to update all the `.pxd` and `.pyx` files to ensure that the import paths are absolute. 

Finally, because of the switch to `python3`, there is an additional compiling error that arises when cythonizing `templated_pbwt_analysis.pyx`. The issue has to do with the integer division being translated to a double on lines 93 and 165:

```
num_cols = sizeof(self.current_matches_start)/sizeof(self.current_matches_start[0])
num_rows = sizeof(self.current_matches_start)/sizeof(self.current_matches_start[0])
```

To make this work, I changed the division to `//`. (Not sure if this would preserve the intended behavior; Please confirm).

Finally, I added a `requirements.txt` file because a friend noticed that the unit tests fail when using newer versions of `pandas`. Please feel free to modify/update this based on your latest tests.

### CODE REVIEW

**Comment by roohy** [comment]
Hi,
May I ask which version of Python/Cython you ended up using. From the pull request, I thought your modifications enabled the use of Cython==3.0.2. However, the version in the requirements file is older. So my questions is, what are the specific versions of all software in case someone uses your pull request? 
I am trying to make a Docker container for this software.

**Comment by shz9** [comment]
Hey, 

It's been a while, but I think the current version should work with both Cython 0.29 and Cython 3.0. As I mentioned in the discussion, the main fix was to make the code compatible with latest versions of `python3`. Maybe it's better to relax the requirements file to say

```
cython>=0.29
```

Or you could remove the version number altogether and grab the latest available from PIP:

```
cython
```

I haven't tested that thoroughly, so you may need to do some basic tests on your end.

**Comment by wf8** [comment]
Hi @shz9 sorry for the very late reply, and thank you very much for making fixes on your branch. I have pushed changes to master that handle the python 3 compilation and a few other dependency issues.
